-- MVP PostgreSQL schema reference, 2026-10-01.
-- For a NEW EMPTY database/schema only. NOT an incremental migration.
-- Do not execute against an existing application database.
-- Existing identity names are preserved; new columns use snake_case.
-- UUIDs are generated by the application (TypeORM/crypto.randomUUID).
-- Service transactions enforce cross-table sums and state transitions.
-- Deployment: one backend process initially, strict module ownership (../SERVICE-OWNERSHIP.md).
-- Auth: users, roles, permissions, users_roles, roles_permissions,
--       auth_sessions, password_reset_challenges, organizer_applications.
-- Event: categories, events, event_reviews.
-- Order: ticket_types, orders, order_items, reservations, tickets, checkins.
-- Payment: payments, payment_notifications. Audit: audit_logs.
-- Cross-owner FK does NOT authorize direct cross-module queries or ORM relations.
-- Cross-module atomic work uses public local ports and an opaque transaction context.
BEGIN;

CREATE TABLE users (
    "idUser" uuid PRIMARY KEY,
    name varchar(150) NOT NULL,
    email varchar(254) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    "emailVerified" boolean NOT NULL DEFAULT false,
    "avatarUrl" text,
    phone varchar(30),
    "resetOTP" varchar(255), -- legacy only: replace with password_reset_challenges
    "resetOTPExpires" timestamp, -- legacy only: do not use for new flow
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    locked_at timestamptz,
    lock_reason text,
    CHECK ((locked_at IS NULL AND lock_reason IS NULL)
        OR (locked_at IS NOT NULL AND lock_reason IS NOT NULL AND btrim(lock_reason) <> '')),
    CHECK (email = lower(btrim(email)))
);

CREATE TABLE roles (
    "idRole" uuid PRIMARY KEY,
    code varchar(64) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    description text,
    "isSystem" boolean NOT NULL DEFAULT false,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
    "idPermission" uuid PRIMARY KEY,
    code varchar(100) NOT NULL UNIQUE,
    name varchar(150) NOT NULL,
    description text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users_roles (
    "idUser" uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    "idRole" uuid NOT NULL REFERENCES roles("idRole") ON DELETE RESTRICT,
    PRIMARY KEY ("idUser", "idRole")
);
CREATE INDEX users_roles_role_idx ON users_roles ("idRole", "idUser");

CREATE TABLE roles_permissions (
    "idRole" uuid NOT NULL REFERENCES roles("idRole") ON DELETE RESTRICT,
    "idPermission" uuid NOT NULL REFERENCES permissions("idPermission") ON DELETE RESTRICT,
    PRIMARY KEY ("idRole", "idPermission")
);
CREATE INDEX roles_permissions_permission_idx ON roles_permissions ("idPermission");

CREATE TABLE auth_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    refresh_token_hash varchar(64) NOT NULL UNIQUE,
    refresh_version integer NOT NULL DEFAULT 0 CHECK (refresh_version >= 0),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    last_used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX auth_sessions_user_idx ON auth_sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX auth_sessions_expiry_idx ON auth_sessions (expires_at);

CREATE TABLE password_reset_challenges (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    otp_hash varchar(64) NOT NULL, -- HMAC with server-side secret, not plain SHA of a short OTP
    failed_attempts smallint NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    invalidated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at),
    CHECK (NOT (consumed_at IS NOT NULL AND invalidated_at IS NOT NULL))
);
CREATE UNIQUE INDEX reset_one_open_per_user_idx ON password_reset_challenges (user_id)
    WHERE consumed_at IS NULL AND invalidated_at IS NULL;
CREATE INDEX reset_expiry_idx ON password_reset_challenges (expires_at);

CREATE TABLE organizer_applications (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    organization_name varchar(200) NOT NULL,
    contact_name varchar(150) NOT NULL,
    contact_email varchar(254) NOT NULL,
    contact_phone varchar(30) NOT NULL,
    description text NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    reviewed_by uuid REFERENCES users("idUser") ON DELETE RESTRICT,
    reviewed_at timestamptz,
    rejection_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL AND rejection_reason IS NULL)
        OR (status = 'APPROVED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NULL)
        OR (status = 'REJECTED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
            AND rejection_reason IS NOT NULL AND btrim(rejection_reason) <> ''))
);
CREATE UNIQUE INDEX organizer_one_pending_idx ON organizer_applications (user_id) WHERE status = 'PENDING';
CREATE UNIQUE INDEX organizer_one_approved_idx ON organizer_applications (user_id) WHERE status = 'APPROVED';
CREATE INDEX organizer_queue_idx ON organizer_applications (status, created_at, id);
CREATE INDEX organizer_user_idx ON organizer_applications (user_id, created_at DESC);

CREATE TABLE categories (
    id uuid PRIMARY KEY,
    name varchar(100) NOT NULL,
    slug varchar(120) NOT NULL UNIQUE,
    description text,
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE events (
    id uuid PRIMARY KEY,
    organizer_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    category_id uuid NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    slug varchar(220) NOT NULL UNIQUE,
    title varchar(200) NOT NULL,
    description text NOT NULL,
    cover_image_url text,
    cover_image_public_id text,
    venue_name varchar(200) NOT NULL,
    address text NOT NULL,
    city_code varchar(32) NOT NULL, -- application-owned location vocabulary
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    checkin_opens_at timestamptz NOT NULL,
    checkin_closes_at timestamptz NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT','PENDING_REVIEW','REJECTED','PUBLISHED','CANCELLED','ARCHIVED')),
    review_version integer NOT NULL DEFAULT 0 CHECK (review_version >= 0),
    submitted_at timestamptz,
    published_at timestamptz,
    sales_paused boolean NOT NULL DEFAULT false,
    checkin_paused boolean NOT NULL DEFAULT false,
    cancelled_at timestamptz,
    cancellation_reason text,
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (starts_at < ends_at),
    CHECK (checkin_opens_at < checkin_closes_at AND checkin_closes_at <= ends_at),
    CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CHECK ((status = 'CANCELLED') = (cancelled_at IS NOT NULL)),
    CHECK (status <> 'CANCELLED' OR (cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')),
    CHECK ((status = 'ARCHIVED') = (archived_at IS NOT NULL))
);
CREATE INDEX events_owner_idx ON events (organizer_id, created_at DESC, id);
CREATE INDEX events_review_queue_idx ON events (submitted_at, id) WHERE status = 'PENDING_REVIEW';
CREATE INDEX events_public_time_idx ON events (starts_at, id) WHERE status = 'PUBLISHED';
CREATE INDEX events_public_category_idx ON events (category_id, starts_at, id) WHERE status = 'PUBLISHED';
CREATE INDEX events_public_city_idx ON events (city_code, starts_at, id) WHERE status = 'PUBLISHED';

CREATE TABLE event_reviews (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    review_version integer NOT NULL CHECK (review_version > 0),
    reviewer_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    decision varchar(16) NOT NULL CHECK (decision IN ('APPROVED','REJECTED')),
    reason text,
    reviewed_snapshot jsonb NOT NULL CHECK (jsonb_typeof(reviewed_snapshot) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, review_version),
    CHECK (decision <> 'REJECTED' OR (reason IS NOT NULL AND btrim(reason) <> ''))
);
CREATE INDEX event_reviews_reviewer_idx ON event_reviews (reviewer_id, created_at DESC);

CREATE TABLE ticket_types (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    name varchar(100) NOT NULL,
    description text,
    price_amount bigint NOT NULL CHECK (price_amount BETWEEN 1 AND 900719925474099),
    capacity integer NOT NULL CHECK (capacity > 0),
    reserved_quantity integer NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    sold_quantity integer NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
    sale_starts_at timestamptz NOT NULL,
    sale_ends_at timestamptz NOT NULL,
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, event_id), -- target of composite FK: ticket type must belong to the order's event
    CHECK (sale_starts_at < sale_ends_at),
    CHECK (reserved_quantity::bigint + sold_quantity <= capacity)
);
CREATE INDEX ticket_types_event_idx ON ticket_types (event_id, price_amount);

CREATE TABLE orders (
    id uuid PRIMARY KEY,
    order_code varchar(32) NOT NULL UNIQUE,
    buyer_id uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    event_id uuid NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
    status varchar(24) NOT NULL DEFAULT 'PENDING_PAYMENT'
        CHECK (status IN ('PENDING_PAYMENT','PAID','EXPIRED','CANCELLED')),
    currency varchar(3) NOT NULL DEFAULT 'VND' CHECK (currency = 'VND'),
    total_quantity smallint NOT NULL CHECK (total_quantity BETWEEN 1 AND 10),
    total_amount bigint NOT NULL CHECK (total_amount BETWEEN 1 AND 9007199254740991),
    buyer_name_snapshot varchar(150) NOT NULL,
    buyer_email_snapshot varchar(254) NOT NULL,
    event_title_snapshot varchar(200) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    request_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL, -- customer checkout deadline; immutable
    paid_payment_id uuid, -- FK added after payments exists
    paid_at timestamptz,
    closed_at timestamptz,
    close_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, event_id),
    UNIQUE (buyer_id, idempotency_key),
    CHECK (expires_at > created_at),
    CHECK ((status = 'PAID' AND paid_payment_id IS NOT NULL AND paid_at IS NOT NULL)
        OR (status <> 'PAID' AND paid_payment_id IS NULL AND paid_at IS NULL)),
    CHECK ((status IN ('EXPIRED','CANCELLED')) = (closed_at IS NOT NULL))
);
CREATE INDEX orders_buyer_idx ON orders (buyer_id, created_at DESC, id);
CREATE INDEX orders_event_status_idx ON orders (event_id, status, created_at DESC, id);
CREATE INDEX orders_expiry_idx ON orders (expires_at, id) WHERE status = 'PENDING_PAYMENT';

CREATE TABLE order_items (
    id uuid PRIMARY KEY,
    order_id uuid NOT NULL,
    event_id uuid NOT NULL,
    ticket_type_id uuid NOT NULL,
    ticket_type_name_snapshot varchar(100) NOT NULL,
    unit_price bigint NOT NULL CHECK (unit_price BETWEEN 1 AND 900719925474099),
    quantity smallint NOT NULL CHECK (quantity BETWEEN 1 AND 10),
    line_total bigint GENERATED ALWAYS AS (unit_price * quantity) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (order_id, ticket_type_id),
    UNIQUE (id, event_id),
    FOREIGN KEY (order_id, event_id) REFERENCES orders(id, event_id) ON DELETE RESTRICT,
    FOREIGN KEY (ticket_type_id, event_id) REFERENCES ticket_types(id, event_id) ON DELETE RESTRICT
);
CREATE INDEX order_items_type_idx ON order_items (ticket_type_id, event_id);

CREATE TABLE reservations (
    order_item_id uuid PRIMARY KEY REFERENCES order_items(id) ON DELETE RESTRICT,
    status varchar(16) NOT NULL DEFAULT 'HELD' CHECK (status IN ('HELD','CONSUMED','RELEASED')),
    release_after timestamptz NOT NULL, -- may extend to provider grace deadline; quantity comes from item
    consumed_at timestamptz,
    released_at timestamptz,
    release_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (release_after > created_at),
    CHECK ((status = 'HELD' AND consumed_at IS NULL AND released_at IS NULL)
        OR (status = 'CONSUMED' AND consumed_at IS NOT NULL AND released_at IS NULL)
        OR (status = 'RELEASED' AND consumed_at IS NULL AND released_at IS NOT NULL))
);
CREATE INDEX reservations_release_idx ON reservations (release_after, order_item_id) WHERE status = 'HELD';

CREATE TABLE payments (
    id uuid PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    provider varchar(40) NOT NULL,
    merchant_account varchar(100) NOT NULL,
    merchant_reference varchar(128) NOT NULL,
    provider_transaction_id varchar(128),
    status varchar(16) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING','UNKNOWN','SUCCEEDED','FAILED')),
    amount bigint NOT NULL CHECK (amount BETWEEN 1 AND 9007199254740991),
    currency varchar(3) NOT NULL DEFAULT 'VND' CHECK (currency = 'VND'),
    checkout_url text, -- do not log signed URLs; validate provider domain in service
    provider_expires_at timestamptz NOT NULL,
    reconcile_until timestamptz NOT NULL, -- finite deadline for retaining inventory
    next_reconcile_at timestamptz,
    last_verified_at timestamptz,
    succeeded_at timestamptz,
    failure_code varchar(100),
    requires_review boolean NOT NULL DEFAULT false,
    review_reason text,
    review_resolved_at timestamptz,
    review_resolved_by uuid REFERENCES users("idUser") ON DELETE RESTRICT,
    review_resolution_note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, order_id),
    UNIQUE (provider, merchant_account, merchant_reference),
    CHECK (provider_expires_at > created_at AND reconcile_until >= provider_expires_at),
    CHECK ((status = 'SUCCEEDED') = (succeeded_at IS NOT NULL)),
    CHECK (NOT requires_review OR (review_reason IS NOT NULL AND btrim(review_reason) <> '')),
    CHECK ((review_resolved_at IS NULL AND review_resolved_by IS NULL AND review_resolution_note IS NULL)
        OR (requires_review AND review_resolved_at IS NOT NULL AND review_resolved_by IS NOT NULL
            AND review_resolution_note IS NOT NULL AND btrim(review_resolution_note) <> ''))
);
CREATE UNIQUE INDEX payments_provider_tx_idx ON payments (provider, merchant_account, provider_transaction_id)
    WHERE provider_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX payments_one_unresolved_idx ON payments (order_id) WHERE status IN ('PENDING','UNKNOWN');
CREATE INDEX payments_order_history_idx ON payments (order_id, created_at DESC);
CREATE INDEX payments_admin_idx ON payments (status, created_at DESC, id);
CREATE INDEX payments_reconcile_idx ON payments (next_reconcile_at, id) WHERE status IN ('PENDING','UNKNOWN');
CREATE INDEX payments_review_idx ON payments (created_at, id) WHERE requires_review AND review_resolved_at IS NULL;
ALTER TABLE orders ADD CONSTRAINT orders_paid_payment_fk
    FOREIGN KEY (paid_payment_id, id) REFERENCES payments(id, order_id) ON DELETE RESTRICT;

CREATE TABLE payment_notifications (
    id uuid PRIMARY KEY,
    payment_id uuid REFERENCES payments(id) ON DELETE RESTRICT,
    provider varchar(40) NOT NULL,
    merchant_account varchar(100) NOT NULL,
    dedupe_key varchar(256) NOT NULL,
    payload_hash varchar(64) NOT NULL,
    sanitized_payload jsonb NOT NULL CHECK (jsonb_typeof(sanitized_payload) = 'object'),
    processing_status varchar(16) NOT NULL DEFAULT 'RECEIVED'
        CHECK (processing_status IN ('RECEIVED','PROCESSED','IGNORED','ERROR')),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_retry_at timestamptz,
    last_error_code varchar(100),
    received_at timestamptz NOT NULL DEFAULT now(),
    processed_at timestamptz,
    UNIQUE (provider, merchant_account, dedupe_key),
    CHECK ((processing_status IN ('PROCESSED','IGNORED')) = (processed_at IS NOT NULL))
);
CREATE INDEX notifications_payment_idx ON payment_notifications (payment_id, received_at DESC);
CREATE INDEX notifications_retry_idx ON payment_notifications (next_retry_at, id)
    WHERE processing_status IN ('RECEIVED','ERROR');

CREATE TABLE tickets (
    id uuid PRIMARY KEY,
    order_item_id uuid NOT NULL,
    event_id uuid NOT NULL,
    sequence_no smallint NOT NULL CHECK (sequence_no BETWEEN 1 AND 10),
    ticket_code varchar(32) NOT NULL UNIQUE, -- random fallback code, still requires organizer authorization
    qr_token_hash varchar(64) NOT NULL UNIQUE,
    qr_token_ciphertext text NOT NULL, -- authenticated encryption; envelope includes nonce/tag
    qr_key_version smallint NOT NULL CHECK (qr_key_version > 0),
    status varchar(16) NOT NULL DEFAULT 'VALID' CHECK (status IN ('VALID','CHECKED_IN','VOID')),
    issued_at timestamptz NOT NULL DEFAULT now(),
    voided_at timestamptz,
    void_reason text,
    UNIQUE (order_item_id, sequence_no),
    UNIQUE (id, event_id),
    FOREIGN KEY (order_item_id, event_id) REFERENCES order_items(id, event_id) ON DELETE RESTRICT,
    CHECK ((status = 'VOID') = (voided_at IS NOT NULL)),
    CHECK (status <> 'VOID' OR (void_reason IS NOT NULL AND btrim(void_reason) <> ''))
);
CREATE INDEX tickets_event_status_idx ON tickets (event_id, status, id);

CREATE TABLE checkins (
    ticket_id uuid PRIMARY KEY,
    event_id uuid NOT NULL,
    checked_in_by uuid NOT NULL REFERENCES users("idUser") ON DELETE RESTRICT,
    checked_in_at timestamptz NOT NULL DEFAULT now(),
    method varchar(16) NOT NULL CHECK (method IN ('QR','MANUAL_CODE')),
    FOREIGN KEY (ticket_id, event_id) REFERENCES tickets(id, event_id) ON DELETE RESTRICT
);
CREATE INDEX checkins_event_time_idx ON checkins (event_id, checked_in_at DESC, ticket_id);
CREATE INDEX checkins_actor_idx ON checkins (checked_in_by, checked_in_at DESC);

CREATE TABLE audit_logs (
    id uuid PRIMARY KEY,
    actor_id uuid REFERENCES users("idUser") ON DELETE RESTRICT,
    actor_kind varchar(16) NOT NULL CHECK (actor_kind IN ('USER','SYSTEM','PROVIDER')),
    action varchar(100) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id uuid NOT NULL, -- polymorphic reference; intentionally not a foreign key
    request_id varchar(128),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((actor_kind = 'USER') = (actor_id IS NOT NULL))
);
CREATE INDEX audit_resource_idx ON audit_logs (resource_type, resource_id, created_at DESC);
CREATE INDEX audit_actor_idx ON audit_logs (actor_id, created_at DESC);

-- Application sets updated_at on all writes, including raw SQL. No timestamp trigger in this reference.
-- Seed USER, ORGANIZER, ADMIN and permissions through an idempotent TypeORM seed, not this DDL.
-- Cross-table invariants and transaction protocols are specified in MVP-DATABASE-DESIGN.md.
COMMIT;
